### ISSUE TITLE
Needs correction 

### ISSUE THREAD

**Issue by afrozchakure** [fanghao6666/neural-networks-and-deep-learning#12]
https://github.com/fanghao6666/neural-networks-and-deep-learning/blob/52908c1bb0f2c6d5957aa2b8af34dac987e10d20/py/Logistic%20Regression%20with%20a%20Neural%20Network%20mindset%20v3.py#L365

should be replace by 
``cost =  (-1 / m ) * np.sum((np.dot(Y, np.log(A).T)) + np.dot((1 - Y), np.log(1 - A).T))  # compute cost``

**Comment by honoreade** [comment]
sure!
